name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies, pull environment, and lint code
        run: |
          npm install
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          npm run lint

      - name: Create preview build
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Success
        run: echo "Deployment successful 😎"
