name: Vercel Prod Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    name: Deploy Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies, pull environment, and lint code
        run: |
          npm install
          npm install --global vercel@latest 
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          npm run lint

      - name: Create prod build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Success
        run: echo "Deployment successful 😎"
